Fix bug reported by Olaf Christ with regards to FFPMEG support.
ffmpeg now requires __STDC_CONSTANT_MACROS to be defined when used from
C++.

WARNING:

If you include videofilebuffer.h, then you will need to compile with
-D__STDC_CONSTANT_MACROS or you will get the following errors:

In file included from /usr/local/include/libavutil/avutil.h:81,
                 from /usr/local/include/libavcodec/avcodec.h:30,
                 from ./cvd/videofilebuffer.h:47,
                 from cvd_src/videofilebuffer.cc:28:
/usr/local/include/libavutil/common.h: In function ‘int32_t av_clipl_int32(int64_t)’:
/usr/local/include/libavutil/common.h:154: error: ‘UINT64_C’ was not declared in this scope